# This is a basic workflow that is manually triggered

name: Build for master branch

on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Setup m2 cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set git email
        run: git config --global user.email "jose.sanchez@modusbox.com"
      - name: Set git name
        run: git config --global user.name "jose.sanchez"

      - name: Get current version without snapshot to tag the docker images
        id: version-to-release
        run: |
          export version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | cut -d- -f1)
          echo "::set-output name=TAG_NAME::$version"

      - name: Print current version
        run: echo "Current version to release ${{ steps.version-to-release.outputs.TAG_NAME }}"

      - name: Prepare release to increment pom version and create tag
        env:
          RELEASE_TAG: ${{ steps.version-to-release.outputs.TAG_NAME  }}
        run:  mvn clean --batch-mode -Dtag=$RELEASE_TAG  release:prepare